"""Add storage directories table

Revision ID: add_storage_dirs
Revises: cd712a173033
Create Date: 2025-09-30 12:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = 'add_storage_dirs'
down_revision = 'cd712a173033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_directories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('owner_type', sa.Enum('ORGANIZATION', 'USER', name='directorytype'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('root_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('current_size_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', name='uq_storage_owner')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_directories')
    op.execute("DROP TYPE IF EXISTS directorytype")
    # ### end Alembic commands ###