# Local Development Configuration
# This configuration uses local services for development and testing

environment: local
debug: true

embedding:
  provider: local
  model_name: "all-MiniLM-L6-v2"  # Lightweight model for development
  cache_folder: "./models"
  device: "cpu"
  batch_size: 16
  max_length: 512

vector_database:
  provider: chromadb
  persist_directory: "./data/chroma_db"
  default_index_name: "knowledge_base"

storage:
  provider: local
  base_path: "./data/storage"
  max_file_size_mb: 100

task_queue:
  provider: redis
  redis_url: "redis://redis:6379/0"
  task_timeout: 3600
  max_retries: 3

state_manager:
  provider: postgresql
  database_url: "postgresql://kb_user:kb_password@postgres:5432/knowledge_base"

workflow:
  provider: local
  max_concurrent_tasks: 2
  default_timeout: 1800

processing:
  chunk_size: 1000
  chunk_overlap: 200
  batch_size: 32
  max_batch_size: 100
  enable_batch_processing: true
  supported_file_types:
    - ".pdf"
    - ".txt"
    - ".md"
    - ".docx"
    - ".html"
  request_timeout: 30
  max_retries: 3

api:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: true
  log_level: "debug"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/knowledge_base.log"
